# Generated by Django 6.0.3 on 2026-03-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('green', 'Green'), ('red', 'Red'), ('blue', 'Blue'), ('pink', 'Pink')], default='white', max_length=50),
        ),
    ]
