# Generated by Django 6.0 on 2026-03-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_category_created_at_alter_category_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='category',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_pinned',
        ),
        migrations.RemoveField(
            model_name='note',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
